services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: 'sbpsql'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=user'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'