spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: 'dialoguesLoaderJob'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  docker:
    compose:
      file: docker-compose.yml
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: user
server:
  port: 9090
